### ISSUE TITLE
Fix ifancy (bin/ifancy) REPL

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#10]
when pressing CTRL-D, for example, ifancy starts an infinate loop.

**Comment by bakkdoor** [comment]
src/bootstrap/console.cc: Return nil if getline() returns EOF. Closed by 2f115c8a033a4d82a178f71945c3e01120b2d971

**Comment by bakkdoor** [comment]
This is actually causing problems again on rbx. Need to fix this again. => Reopened

**Comment by bakkdoor** [comment]
Made bin/ifancy work (mostly). Still some problems with assigning variables to locals etc. that need to be fixed. Closed by b2642e4dc0a27766ef661aed81450cb70859b9a9

**Comment by bakkdoor** [comment]
Reopened: ifancy doesn't currently correctly handle local variable assignments, as well as printing out the value of the last entered expression, it just always prints `true`. I suppose this has to do with how the parser works.

**Comment by vic** [comment]
Actually this is because of how Fancy.eval works .. we're acutally cheating on eval, we compile the fancy code, but load it using the same code loader as we do when you require a file. That's why it always returns true (true is returned when the file was loaded). What we actually have to do is get eval_fix_me method from eval.rb to work.

**Comment by bakkdoor** [comment]
Ah ok, I'll probably have a look at it later, but if you want to work on that, go for it ;)

**Comment by bakkdoor** [comment]
Is fixed as of bf8c3900e468088a0b4230eaa82d664732eabf53
